# Generated by Django 3.0.6 on 2020-06-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='book_image/default.png', upload_to='book_image/'),
        ),
    ]
