# Generated by Django 3.0.6 on 2020-06-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200609_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
