# Generated by Django 3.0.6 on 2020-06-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200609_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='/images/default.png', upload_to='images'),
        ),
    ]
