# Generated by Django 3.0.6 on 2020-06-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200609_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.FileField(default='/images/default.png', upload_to='images'),
        ),
    ]
